/** Techizmet Shop mirror *-tr.html — toplu EN→TR çeviri sözlüğü (uzun metinler önce eklenir) */

export const MIRROR_TR_CATALOG: ReadonlyArray<readonly [string, string]> = [
  // —— Ana sayfa: media grid ——
  [
    'Unleash your inner radiance with our curated Beauty Essentials — a collection designed to enhance your natural glow. Packed with skin-loving ingredients and gentle formulas, each product works harmoniously to nourish, hydrate, and revitalize your skin. Whether you\'re starting your day or winding down, these essentials help you feel confident, fresh, and beautifully you.',
    'İç ışığınızı öne çıkarın: Beauty Essentials koleksiyonumuz doğal parlaklığınızı artırmak için tasarlandı. Cilde sevgi dolu içerikler ve nazik formüllerle her ürün cildinizi besler, nemlendirir ve canlandırır. Güne başlarken veya akşam dinlenirken kendinizi özgüvenli, taze ve güzel hissedin.',
  ],
  [
    "Unleash your inner radiance with our curated Beauty Essentials - a collection designed to enhance your natural glow. Packed with skin-loving ingredients and gentle formulas, each product works harmoniously to nourish, hydrate, and revitalize your skin. Whether you're starting your day or winding down, these essentials help you feel confident, fresh, and beautifully you.",
    'İç ışığınızı öne çıkarın: Beauty Essentials koleksiyonumuz doğal parlaklığınızı artırmak için tasarlandı. Cilde sevgi dolu içerikler ve nazik formüllerle her ürün cildinizi besler, nemlendirir ve canlandırır. Güne başlarken veya akşam dinlenirken kendinizi özgüvenli, taze ve güzel hissedin.',
  ],
  [
    "Rejuvenate your skin with our vitamin-enriched face and body creams, specially formulated to deeply nourish, hydrate, and restore your skin's natural glow. Packed with essential nutrients like Vitamins C, E, and B5, our creams help repair damage, improve texture, and protect against environmental stressors. Whether you're targeting dryness, dullness, or uneven tone, our lightweight yet powerful formula absorbs quickly and leaves your skin feeling soft, smooth, and revitalized — from head to toe.",
    "Cildinizi vitamin destekli yüz ve vücut kremlerimizle yenileyin; derinlemesine besler, nemlendirir ve doğal ışıltınızı geri kazandırır. C, E ve B5 vitaminleri ile hasarı onarır, dokuyu iyileştirir ve çevresel strese karşı korur. Kuru, mat veya ton eşitsizliği için hızlı emilen formül baştan ayağa yumuşak ve canlı bir his bırakır.",
  ],
  [
    "Rejuvenate your skin with our vitamin-enriched face and body creams, specially formulated to deeply nourish, hydrate, and restore your skin's natural glow. Packed with essential nutrients like Vitamins C, E, and B5, our creams help repair damage, improve texture, and protect against environmental stressors. Whether you're targeting dryness, dullness, or uneven tone, our lightweight yet powerful formula absorbs quickly and leaves your skin feeling soft, smooth, and revitalized - from head to toe.",
    "Cildinizi vitamin destekli yüz ve vücut kremlerimizle yenileyin; derinlemesine besler, nemlendirir ve doğal ışıltınızı geri kazandırır. C, E ve B5 vitaminleri ile hasarı onarır, dokuyu iyileştirir ve çevresel strese karşı korur. Kuru, mat veya ton eşitsizliği için hızlı emilen formül baştan ayağa yumuşak ve canlı bir his bırakır.",
  ],
  [
    "Enriched with potent ingredients like hyaluronic acid, peptides, ceramides, and natural botanical extracts, our night creams work to repair environmental damage, boost collagen production, and improve skin elasticity.",
    "Hyalüronik asit, peptitler, seramidler ve doğal bitki özleri gibi güçlü içeriklerle gece kremlerimiz çevresel hasarı onarır, kolajen üretimini destekler ve cilt elastikiyetini artırır.",
  ],
  [
    "Gently nourish and protect your skin with our specially formulated organic skincare range, designed for sensitive skin.",
    "Hassas cilt için özel olarak formüle edilmiş organik cilt bakım serimizle cildinizi nazikçe besleyin ve koruyun.",
  ],
  [
    'Glow Naturally with Our <span class="markers-text accent-font highlight-color">Beauty Essentials</span>',
    'Doğal Işıltınızı <span class="markers-text accent-font highlight-color">Güzellik Esansiyalleri</span> ile Keşfedin',
  ],
  [
    'Restore with Our Vitamin Infused <span class="markers-text accent-font highlight-color">Face & Body</span>',
    'Vitamin Destekli <span class="markers-text accent-font highlight-color">Yüz & Vücut</span> Bakımı ile Yenileyin',
  ],
  [
    'Organic Skincare for <span class="markers-text accent-font no-markers">Sensitive Skin</span>',
    'Hassas Cilt için <span class="markers-text accent-font no-markers">Organik Cilt Bakımı</span>',
  ],
  [
    'Skincare <span class="markers-text accent-font no-markers">Collection</span>',
    'Cilt Bakımı <span class="markers-text accent-font no-markers">Koleksiyonu</span>',
  ],
  [
    'Skincare <span class="markers-text accent-font no-markers">Essentials Deals</span>',
    'Cilt Bakımı <span class="markers-text accent-font no-markers">Fırsatları</span>',
  ],
  ['Customer <span class="markers-text accent-font no-markers">Love & Feedback</span>', 'Müşteri <span class="markers-text accent-font no-markers">Yorumları</span>'],
  ['Love & Feedback', 'Yorumlar'],
  // —— Trend ürünler ——
  [
    "Reveal visibly firmer, smoother, and more youthful-looking skin with the Micro-Sculpting Moisturizer.",
    "Mikro Şekillendirici Nemlendirici ile daha sıkı, pürüzsüz ve genç görünümlü bir cilt.",
  ],
  [
    "This ultra-light, non-greasy formula absorbs quickly to deliver instant moisture and a smooth, dewy finish.",
    "Bu ultra hafif, yağsız formül hızla emilerek anında nem ve pürüzsüz, ışıltılı bir bitiş sağlar.",
  ],
  ["Micro-Sculpting Moisturizer", "Mikro Şekillendirici Nemlendirici"],
  ["Image of Micro-Sculpting Moisturizer", "Mikro Şekillendirici Nemlendirici Görseli"],
  ["View details of Micro-Sculpting Moisturizer", "Mikro Şekillendirici Nemlendirici detayları"],
  ["View details of Anti-Cellulite Body Oil", "Anti-Selülit Vücut Yağı detayları"],
  ["Image of Anti-Cellulite Body Oil", "Anti-Selülit Vücut Yağı Görseli"],
  ['data-text="Beauty"', 'data-text="Güzellik"'],
  [">Beauty<", ">Güzellik<"],
  ["VIEW DETAIL", "DETAYLARI GÖR"],
  ["• VIEW DETAIL", "• DETAYLARI GÖR"],
  // —— Müşteri yorumları ——
  [
    "I've tried many skincare brands, but these products truly stand out. My skin feels nourished, hydrated, and glowing. The natural ingredients make a huge difference.",
    "Birçok cilt bakım markası denedim ama bu ürünler gerçekten fark yaratıyor. Cildim beslenmiş, nemli ve ışıltılı hissediyor. Doğal içerikler büyük fark yaratıyor.",
  ],
  [
    "After using this skincare line for a month, my complexion looks clearer and more even. The formulas are gentle yet effective, leaving my skin soft without any irritation at all.",
    "Bu cilt bakım serisini bir ay kullandıktan sonra tenim daha berrak ve eşit görünüyor. Formüller nazik ama etkili; cildim tahriş olmadan yumuşak kalıyor.",
  ],
  [
    "The hydration boost is incredible! My dry skin feels replenished and smooth all day. I love how lightweight the products feel while delivering powerful results.",
    "Nem desteği inanılmaz! Kuru cildim gün boyu dolu ve pürüzsüz hissediyor. Ürünler hafif ama güçlü sonuç veriyor.",
  ],
  [
    "I'm impressed with how quickly I noticed improvements. Fine lines softened, and my skin's texture became smoother. Plus, knowing it's cruelty-free makes me feel good.",
    "İyileşmeleri ne kadar çabuk fark ettiğime şaşırdım. İnce çizgiler yumuşadı, cilt dokum düzeldi. Ayrıca hayvanlar üzerinde test edilmemesi beni mutlu ediyor.",
  ],
  [
    "These skincare essentials are a game changer! They absorb quickly and don't leave any greasy residue. My skin feels fresh, healthy, and more radiant every morning. I'm hooked!",
    "Bu cilt bakım esansiyelleri oyun değiştirici! Hızla emiliyor ve yağlı kalıntı bırakmıyor. Her sabah cildim taze, sağlıklı ve daha ışıltılı. Bayıldım!",
  ],
  // —— Ürün adları (tüm vitrin) ——
  ["24HR Smudge-Proof Mascara", "24 Saat Akılmaz Maskara"],
  ["Anti-Cellulite Body Oil", "Anti-Selülit Vücut Yağı"],
  ["Berry Tint Lip Balm", "Berry Renkli Dudak Balmı"],
  ["Daily Use Face Moisturizer", "Günlük Yüz Nemlendirici"],
  ["Dewmist Hydrating Makeup Fixer", "Dewmist Nemlendirici Makyaj Sabitleyici"],
  ["Ultra-Fine Hydration Mist", "Ultra İnce Nemlendirici Mist"],
  ["Vitamin C Hyaluronic Acid Radiant Serum", "C Vitamini Hyalüronik Asit Aydınlatıcı Serum"],
  ["Skinglow Moisture Boost Serum", "Skinglow Nem Artırıcı Serum"],
  ["Hydrasilk Skin Reviving Cleanser", "Hydrasilk Canlandırıcı Temizleyici"],
  ["Hydrasoft Face Moisturizer", "Hydrasoft Yüz Nemlendiricisi"],
  ["Spectrum Sunscreen SPF 50", "Spectrum Güneş Kremi SPF 50"],
  ["Smooth Finish HD Concealer", "Pürüzsüz HD Kapatıcı"],
  ["Liquid Foundation SPF 30", "Sıvı Fondöten SPF 30"],
  ["Flawless Silkskin Foundation", "Kusursuz İpeksi Fondöten"],
  ["Creamy Foundation for All Skin Types", "Tüm Cilt Tipleri için Kremsi Fondöten"],
  ["Dual Contour Bronzer Set", "Çift Kontür Bronzer Seti"],
  ["Long Lasting Make Up Fixer", "Uzun Süre Kalıcı Makyaj Sabitleyici"],
  ["Floral Eau De Parfum Long Lasting", "Çiçeksi Uzun Süre Kalıcı Parfüm"],
  ["Hydrating Shampoo for Soft Smooth Hair", "Yumuşak Saçlar için Nemlendirici Şampuan"],
  // —— Ürün açıklamaları (ortak) ——
  [
    "Micro-Sculpting Moisturizer is a scientifically formulated cream designed to hydrate deeply while improving skin elasticity and firmness. Its advanced blend of ingredients supports collagen production and reduces the appearance of fine lines and wrinkles. Ideal for daily use, this moisturizer enhances skin texture and promotes a youthful, sculpted complexion.",
    "Mikro Şekillendirici Nemlendirici, cildi derinlemesine nemlendirirken elastikiyet ve sıkılığı artırmak için bilimsel olarak formüle edilmiş bir kremdir. Gelişmiş içerik karışımı kolajen üretimini destekler, ince çizgi ve kırışıklık görünümünü azaltır. Günlük kullanım için idealdir.",
  ],
  ["View details of ", "Ürün detayı: "],
  ["View detailsfor ", "Ürün detayı: "],
  ["Blog Post", "Blog Yazısı"],
  ["June 23, 2025", "23 Haziran 2025"],
  ["Shine Dezign", "Shine Dezign"],
  ["Read more", "Devamını oku"],
  ["Shop now", "Hemen al"],
  ["Learn more", "Daha fazla bilgi"],
  ["Discover", "Keşfet"],
  ["Sensitive Skin", "Hassas Cilt"],
  ["Beauty Essentials", "Güzellik Esansiyelleri"],
  ["Face & Body", "Yüz & Vücut"],
  ["Glow Naturally with Our", "Doğal Işıltınızı Keşfedin —"],
  ["Restore with Our Vitamin Infused", "Vitamin Destekli Bakım —"],
  ["Organic Skincare for", "Organik Cilt Bakımı —"],
  ["Pure Beauty", "Saf Güzellik"],
  ["SILKEN", "İPEKİ"],
  ["Trending", "Trend"],
  ["Featured", "Öne çıkan"],
  ["New Arrival", "Yeni gelen"],
  ["Best Seller", "Çok satan"],
  ["Sale", "İndirim"],
  ["Free shipping", "Ücretsiz kargo"],
  ["Subscribe", "Abone ol"],
  ["Notify me", "Haber ver"],
  ["Write a review", "Yorum yaz"],
  ["Related products", "İlgili ürünler"],
  ["You may also like", "Bunları da beğenebilirsiniz"],
  ["Description", "Açıklama"],
  ["Ingredients", "İçerikler"],
  ["How to use", "Nasıl kullanılır"],
  ["Reviews", "Yorumlar"],
  ["Shipping", "Kargo"],
  ["Returns", "İadeler"],
  ["Size", "Boyut"],
  ["Color", "Renk"],
  ["Quantity", "Adet"],
  ["Subtotal", "Ara toplam"],
  ["Total", "Toplam"],
  ["Checkout", "Ödeme"],
  ["Continue shopping", "Alışverişe devam"],
  ["Update", "Güncelle"],
  ["Remove", "Kaldır"],
  ["Apply", "Uygula"],
  ["Close", "Kapat"],
  ["Menu", "Menü"],
  ["Wishlist", "Favoriler"],
  ["Compare", "Karşılaştır"],
  ["Sign in", "Giriş yap"],
  ["Sign up", "Kayıt ol"],
  ["My account", "Hesabım"],
  ["Track order", "Sipariş takibi"],
  ["All rights reserved", "Tüm hakları saklıdır"],
  // —— Ek müşteri yorumları ——
  [
    "My sensitive skin is finally calm and balanced thanks to this product range. No redness or irritation, just clean, nourished skin that glows with health. Truly recommend.",
    "Hassas cildim bu ürün serisi sayesinde sonunda sakin ve dengeli. Kızarıklık veya tahriş yok; temiz, beslenmiş ve sağlıklı ışıltılı cilt. Kesinlikle tavsiye ederim.",
  ],
  [
    "The natural ingredients make all the difference. I noticed fewer breakouts and my skin tone is much more even. These products have become my daily must-have for skincare.",
    "Doğal içerikler tüm farkı yaratıyor. Daha az sivilce ve çok daha eşit bir ten fark ettim. Bu ürünler günlük cilt bakımımın vazgeçilmezi oldu.",
  ],
  [
    "It encourages confidence in your skin, celebrating every feature without the need for heavy coverage or drastic change.",
    "Cildinize güven duymanızı teşvik eder; ağır kapatıcı veya köklü değişim olmadan her özelliğinizi kutlar.",
  ],
  [
    "Instead of masking imperfections, it focuses on nurturing and highlighting your unique glow with gentle, effective skincare.",
    "Kusurları gizlemek yerine, nazik ve etkili cilt bakımıyla benzersiz ışıltınızı beslemeye ve öne çıkarmaya odaklanır.",
  ],
  [
    "Packed with skin-loving ingredients and gentle formulas, each product works harmoniously to nourish, hydrate, and revitalize your skin.",
    "Cilde sevgi dolu içerikler ve nazik formüllerle her ürün cildinizi uyum içinde besler, nemlendirir ve canlandırır.",
  ],
  [
    "Whether you're starting your day or winding down, these essentials help you feel confident, fresh, and beautifully you.",
    "Güne başlarken veya günü kapatırken bu esansiyeller özgüvenli, taze ve güzel hissetmenize yardımcı olur.",
  ],
  [
    "Packed with essential nutrients like Vitamins C, E, and B5, our creams help repair damage, improve texture, and protect against environmental stressors.",
    "C, E ve B5 gibi temel besinlerle kremlerimiz hasarı onarır, dokuyu iyileştirir ve çevresel strese karşı korur.",
  ],
  [
    "Whether you're targeting dryness, dullness, or uneven tone, our lightweight yet powerful formula absorbs quickly and leaves your skin feeling soft, smooth, and revitalized — from head to toe.",
    "Kuruluk, matlık veya ton eşitsizliği için hafif ama güçlü formül hızla emilir; cildiniz baştan ayağa yumuşak ve canlı hisseder.",
  ],
  // —— Koleksiyon adları ——
  ["Facial Boosters", "Yüz Güçlendiriciler"],
  ["Glow Essentials", "Işıltı Esansiyelleri"],
  ["Luxe Skincare", "Lüks Cilt Bakımı"],
  ["Moisture Magic", "Nem Sihri"],
  ["Natural Glam", "Doğal Işıltı"],
  ["Pure by Nature", "Doğadan Saf"],
  ["Image of Facial Boosters", "Yüz Güçlendiriciler Görseli"],
  ["Image of Glow Essentials", "Işıltı Esansiyelleri Görseli"],
  ["Image of Luxe Skincare", "Lüks Cilt Bakımı Görseli"],
  ["BOGO Sale", "1 Alana 1 Bedava"],
  ['data-text="BOGO Sale"', 'data-text="1 Alana 1 Bedava"'],
  // —— Ana sayfa: kullanıcı bildirimi — kalan İngilizce ——
  [
    'Something special for every <span class="markers-text accent-font no-markers">Occasion.</span>',
    'Her an için özel bir şey <span class="markers-text accent-font no-markers">Sizin için.</span>',
  ],
  ["Something special for every Occasion.", "Her an için özel bir şey."],
  [
    'Flash Sale <span class="markers-text accent-font no-markers">Starts Now!</span>',
    'Flaş İndirim <span class="markers-text accent-font no-markers">Başladı!</span>',
  ],
  ["Flash Sale Starts Now!", "Flaş İndirim Başladı!"],
  [
    "Luxurious skincare essentials on sale now stock up fast before the best deals end.",
    "Lüks cilt bakım esansiyellerinde indirim; en iyi fırsatlar bitmeden stokları kaçırmayın.",
  ],
  [
    'Special <span class="markers-text accent-font no-markers">Launch Offer</span>',
    'Özel <span class="markers-text accent-font no-markers">Lansman Fırsatı</span>',
  ],
  ["Special Launch Offer", "Özel Lansman Fırsatı"],
  [
    'Healthy glowing skin begins with pure and <span class="markers-text accent-font no-markers">Simple skincare love</span>',
    'Sağlıklı ışıltılı cilt saf ve <span class="markers-text accent-font no-markers">basit cilt bakımı sevgisi</span> ile başlar',
  ],
  [
    "Nourish your skin with the gentle care it truly deserves. Our skincare is crafted with clean, effective ingredients that hydrate, protect, and restore — all without the harsh additives. Fall in love with your natural glow through a simple, pure routine that puts your skin first. Radiance starts with kindness.",
    "Cildinizi hak ettiği nazik bakımla besleyin. Temiz, etkili içeriklerle formüle edilmiş ürünlerimiz nemlendirir, korur ve yeniler — sert katkı maddeleri olmadan. Basit, saf bir rutinle doğal ışıltınıza aşık olun. Işıltı nezaketle başlar.",
  ],
  [
    "Nourish your skin with the gentle care it truly deserves. Our skincare is crafted with clean, effective ingredients that hydrate, protect, and restore - all without the harsh additives. Fall in love with your natural glow through a simple, pure routine that puts your skin first. Radiance starts with kindness.",
    "Cildinizi hak ettiği nazik bakımla besleyin. Temiz, etkili içeriklerle formüle edilmiş ürünlerimiz nemlendirir, korur ve yeniler — sert katkı maddeleri olmadan. Basit, saf bir rutinle doğal ışıltınıza aşık olun. Işıltı nezaketle başlar.",
  ],
  [
    '<span class="markers-text heading-font outline--filled">EXTRA 20% OFF WITH CODE: GLOW20</span>',
    '<span class="markers-text heading-font outline--filled">GLOW20 KODU İLE EKSTRA %20 İNDİRİM</span>',
  ],
  ["EXTRA 20% OFF WITH CODE: GLOW20", "GLOW20 kodu ile ekstra %20 indirim"],
  [">EXPLORE<", ">KEŞFET<"],
  ["EXPLORE", "KEŞFET"],
  [
    "Hydration Is Key for Healthy, Youthful Skin",
    "Sağlıklı, Genç Görünümlü Cilt İçin Nemlendirme",
  ],
  [
    "Image of Hydration Is Key for Healthy, Youthful Skin",
    "Sağlıklı Genç Cilt İçin Nemlendirme Görseli",
  ],
  [
    "When it comes to skincare, one essential factor often overlooked is hydration. Whether your skin is dry, oily, or somewhere",
    "Cilt bakımında sık göz ardı edilen bir faktör nemlendirmedir. Cildiniz kuru, yağlı veya karma olsun",
  ],
  // —— Kategori şeridi ——
  ["Cleansers", "Temizleyiciler"],
  ["Moisturizers", "Nemlendiriciler"],
  ["Sun Protection", "Güneş Koruma"],
  ["Makeup", "Makyaj"],
  ["Bath & Body", "Banyo & Vücut"],
  ["Toners", "Tonikler"],
  ["Kits & Combos", "Setler & Kombinler"],
  ["Face Oils", "Yüz Yağları"],
  ["Eye Care", "Göz Bakımı"],
  ["Lip Care", "Dudak Bakımı"],
  ["Masks", "Maskeler"],
  ["Gifts Set", "Hediye Setleri"],
  // —— Ürün / UI (eksik) ——
  ["Makeup Fixer", "Makyaj Sabitleyici"],
  ["Long Lasting Make Up Fixer", "Uzun Süre Kalıcı Makyaj Sabitleyici"],
  ["DewMist Hydrating Makeup Fixer", "DewMist Nemlendirici Makyaj Sabitleyici"],
  ["Image of Makeup Fixer", "Makyaj Sabitleyici Görseli"],
  ["Quick view of Makeup Fixer", "Makyaj Sabitleyici hızlı önizleme"],
  ["View detailsfor Makeup Fixer", "Makyaj Sabitleyici detayları"],
  ["View detailsfor DewMist Hydrating Makeup Fixer", "DewMist Makyaj Sabitleyici detayları"],
  ["Plus, knowing it's cruelty-free makes me feel good.", "Ayrıca hayvanlar üzerinde test edilmemesi beni mutlu ediyor."],
  ["I'm hooked!", "Bayıldım!"],
  ["Truly recommend.", "Kesinlikle tavsiye ederim."],
  ["Quick view of ", "Hızlı önizleme: "],
  ["Quick view", "Hızlı önizleme"],
  ["Add to wishlist", "Favorilere ekle"],
  ["Remove from wishlist", "Favorilerden çıkar"],
  ["Quick add", "Hızlı ekle"],
  ["Choose options", "Seçenekleri seç"],
  ["From ", "Başlangıç "],
  ["Save ", "Tasarruf "],
  ["OFF", "İNDİRİM"],
  ["New", "Yeni"],
  ["Popular", "Popüler"],
  ["All products", "Tüm ürünler"],
  ["Haircare", "Saç Bakımı"],
  ["Body care", "Vücut Bakımı"],
  ["Shop all", "Tümünü gör"],
  ["Shop All", "Tümünü Gör"],
  ["See all", "Tümünü gör"],
  ["See All", "Tümünü Gör"],
  ["View all", "Tümünü gör"],
  ["View All", "Tümünü Gör"],
  ["Load more", "Daha fazla yükle"],
  ["Show more", "Daha fazla göster"],
  ["Show less", "Daha az göster"],
  ["Email address", "E-posta adresi"],
  ["Your email", "E-posta adresiniz"],
  ["Subscribe to newsletter", "Bültene abone ol"],
  ["Thank you for subscribing", "Abone olduğunuz için teşekkürler"],
  ["Enter your email", "E-posta adresinizi girin"],
  ["Follow us", "Bizi takip edin"],
  ["Follow Us", "Bizi Takip Edin"],
  ["Our story", "Hikayemiz"],
  ["Our Story", "Hikayemiz"],
  ["Contact us", "Bize ulaşın"],
  ["Contact Us", "Bize Ulaşın"],
  ["Get in touch", "İletişime geçin"],
  ["Customer service", "Müşteri hizmetleri"],
  ["FAQ", "SSS"],
  ["FAQs", "SSS"],
  ["Shipping policy", "Kargo politikası"],
  ["Shipping Policy", "Kargo Politikası"],
  ["Enhance Your Natural Beauty", "Doğal Güzelliğinizi Öne Çıkarın"],
  ["Enhance Your Natural Beauty is more than just a tagline", "Doğal güzelliğinizi öne çıkarmak yalnızca bir slogan değil"],
  ["Indulge in the Natural Skincare Collection", "Doğal Cilt Bakımı Koleksiyonunun keyfini çıkarın"],
  ["Latest Skincare Tips", "Son Cilt Bakımı İpuçları"],
  ["Top Natural Ingredients for Glowing Skin", "Parlayan Cilt İçin En İyi Doğal İçerikler"],
  ["Build the Perfect Skincare Routine", "Mükemmel Cilt Bakımı Rutini Oluşturun"],
  ["Customer Love & Feedback", "Müşteri Yorumları"],
  ["Customer Love", "Müşteri Yorumları"],
  ["Trending Products", "Trend Ürünler"],
  ["Best Selling Products", "Çok Satan Ürünler"],
  ["Featured Collection", "Öne Çıkan Koleksiyon"],
  ["Shop The Look", "Stilini Keşfet"],
  ["Shop the look", "Stilini keşfet"],
  ["Add to bag", "Sepete ekle"],
  ["Buy now", "Hemen al"],
  ["Buy Now", "Hemen Al"],
  // —— Ürün sayfası (PDP) — stok, rozetler, tonlar ——
  ["In stock, ready to be shipped", "Stokta, kargoya hazır"],
  ["Stokta, ready to be shipped", "Stokta, kargoya hazır"],
  ["ready to be shipped", "kargoya hazır"],
  ["Deep Hydra", "Derin Nem"],
  ["Lab Tested", "Laboratuvar Testli"],
  ["Glow Boost", "Işıltı Artırıcı"],
  ["Deep Purify", "Derin Arındırma"],
  ["Smart Formula", "Akıllı Formül"],
  ["Nourishment", "Besleyici"],
  ["Youthful", "Genç Görünüm"],
  ["Natural Ingredients", "Doğal İçerikler"],
  ["Hydrating", "Nemlendirici"],
  ["Key Features", "Öne Çıkan Özellikler"],
  ["How to Use", "Nasıl Kullanılır"],
  ["Light Ivory", "Açık Fildişi"],
  ["Beige Neutral", "Bej Nötr"],
  ["Warm Tan", "Sıcak Ten"],
  ["Deep Mocha", "Koyu Mocha"],
  ["Creamy Foundation", "Kremsi Fondöten"],
  ["Hyaluronic Acid Serum", "Hyalüronik Asit Serumu"],
  ["Ultra-Fine Hydration Pure Mist", "Ultra İnce Nemlendirici Mist"],
  ["Spectrum Sunscreen SPF 50", "Spectrum Güneş Kremi SPF 50"],
  ["Smooth Finish HD Concealer", "Pürüzsüz HD Kapatıcı"],
  ["SkinGlow Moisture Boost Serum", "Skinglow Nem Artırıcı Serum"],
  ["Makeup Fixer", "Makyaj Sabitleyici"],
  ["Liquid Foundation + SPF 30", "Sıvı Fondöten SPF 30"],
  ["Hydrating Shampoo", "Nemlendirici Şampuan"],
  ["HydraSoft Face Moisturizer", "Hydrasoft Yüz Nemlendiricisi"],
  ["HydraSilk Skin Reviving Cleanser", "Hydrasilk Canlandırıcı Temizleyici"],
  ["Floral Eau de Parfum", "Çiçeksi Parfüm"],
  ["Flawless Silkskin Foundation", "Kusursuz İpeksi Fondöten"],
  ["Dual Contour &amp; Bronzer Set", "Çift Kontür ve Bronzer Seti"],
  ["Dual Contour & Bronzer Set", "Çift Kontür ve Bronzer Seti"],
  ["DewMist Hydrating Makeup Fixer", "DewMist Nemlendirici Makyaj Sabitleyici"],
  ["Daily Use Face Moisturizer", "Günlük Yüz Nemlendirici"],
  ["Berry Tint Lip Balm", "Berry Renkli Dudak Balmı"],
  ["Anti-Cellulite Body Oil", "Anti-Selülit Vücut Yağı"],
  ["24HR Smudge-Proof Mascara", "24 Saat Akılmaz Maskara"],
  [
    "Ideal for achieving a flawless, professional finish with lasting wear.",
    "Kusursuz, profesyonel ve kalıcı bir bitiş için idealdir.",
  ],
  [
    "This creamy foundation offers a smooth, blendable formula suitable for all skin types, providing even coverage that enhances your natural complexion. Its hydrating properties ensure a comfortable wear throughout the day, while the lightweight texture prevents clogging pores. Ideal for achieving a flawless, professional finish with lasting wear.",
    "Bu kremsi fondöten tüm cilt tiplerine uygun, kolay yayılan bir formüle sahiptir; doğal ten renginizi öne çıkaran eşit bir kapatıcılık sunar. Nemlendirici yapısı gün boyu konforlu kullanım sağlar, hafif dokusu gözenekleri tıkamaz. Kusursuz, profesyonel ve kalıcı bir bitiş için idealdir.",
  ],
  [
    "Ideal for daily use, this moisturizer enhances skin texture and promotes a youthful, sculpted complexion.",
    "Günlük kullanım için idealdir; cilt dokusunu iyileştirir ve genç, şekilli bir görünüm sağlar.",
  ],
  [
    "This serum supports a radiant, youthful complexion through scientifically backed ingredients designed for effective skincare results.",
    "Bu serum, etkili cilt bakımı için tasarlanmış bilimsel içeriklerle ışıltılı ve genç bir cilt görünümünü destekler.",
  ],
  [
    "Must have this for reliable, professional-quality results that maintain a fresh look throughout the day.",
    "Gün boyu taze bir görünüm sunan, güvenilir ve profesyonel kalitede sonuçlar için vazgeçilmezdir.",
  ],
  [
    "Ideal for all skin types, it enhances makeup durability while maintaining comfort.",
    "Tüm cilt tipleri için idealdir; konforu korurken makyaj dayanıklılığını artırır.",
  ],
  [
    "Ideal for all skin types, this fixer enhances makeup longevity without clogging pores, ensuring a comfortable, radiant look from morning to night.",
    "Tüm cilt tipleri için idealdir; gözenekleri tıkamadan makyajın kalıcılığını artırır, sabah akşam konforlu ve ışıltılı bir görünüm sağlar.",
  ],
  [
    "Ideal for all skin types, this foundation offers long-lasting wear and a silky texture that feels comfortable throughout the day.",
    "Tüm cilt tipleri için idealdir; uzun süre kalıcıdır ve gün boyu konforlu, ipeksi bir doku sunar.",
  ],
  [
    "Ideal for all skin types, this concealer enhances your complexion while maintaining a smooth, radiant look throughout the day.",
    "Tüm cilt tipleri için idealdir; teninizi öne çıkarır ve gün boyu pürüzsüz, ışıltılı bir görünüm korur.",
  ],
  [
    "Ideal for all skin types, this mist helps maintain optimal hydration levels throughout the day, enhancing skin's natural radiance and comfort.",
    "Tüm cilt tipleri için idealdir; gün boyu optimal nem seviyesini korur, cildin doğal ışıltısını ve konforunu artırır.",
  ],
  [
    "Ideal for all skin types, it supports skin's natural moisture barrier and helps maintain a healthy, radiant complexion with regular use.",
    "Tüm cilt tipleri için idealdir; cildin doğal nem bariyerini destekler, düzenli kullanımda sağlıklı ve ışıltılı bir görünüm sağlar.",
  ],
  [
    "Ideal for daily use, this moisturizer supports a healthy, radiant complexion by reinforcing the skin's natural barrier and preventing dryness.",
    "Günlük kullanım için idealdir; cildin doğal bariyerini güçlendirerek kuruluğu önler ve sağlıklı, ışıltılı bir görünüm sunar.",
  ],
  [
    "Ideal for all hair types, it enhances shine and reduces frizz, providing a silky texture that lasts throughout the day.",
    "Tüm saç tipleri için idealdir; parlaklığı artırır, elektriklenmeyi azaltır ve gün boyu ipeksi bir doku sağlar.",
  ],
  [
    "Ideal for regular use, this lightweight oil absorbs quickly without leaving a greasy residue, making it a practical addition to your skincare routine.",
    "Düzenli kullanım için idealdir; hafif yağ hızla emilir, yağlı kalıntı bırakmaz; cilt bakım rutininize pratik bir eklemedir.",
  ],
  [
    "Ideal for creating depth and dimension, it suits all skin tones and provides a smooth, buildable finish for professional contouring and bronzing results.",
    "Derinlik ve boyut kazandırmak için idealdir; tüm ten tonlarına uygundur, profesyonel kontür ve bronzlaştırma için katmanlanabilir pürüzsüz bir bitiş sunar.",
  ],
  [
    "Ideal for those seeking a timeless, enduring scent that complements any occasion.",
    "Her ortama uyum sağlayan, zamansız ve kalıcı bir koku arayanlar için idealdir.",
  ],
  [
    "Enriched with sun protection, it helps prevent premature aging and sun damage, ensuring your complexion stays radiant and healthy throughout the day.",
    "Güneş koruması ile zenginleştirilmiştir; erken yaşlanma ve güneş hasarını önlemeye yardımcı olur, teninizin gün boyu ışıltılı ve sağlıklı kalmasını sağlar.",
  ],
  [
    "Dermatologists recommended for healthy skin with reliable, high-performance sun protection.",
    "Sağlıklı cilt için dermatologların önerdiği, güvenilir ve yüksek performanslı güneş koruması.",
  ],
  [
    "Must have for a healthy complexion without stripping essential oils, promoting a radiant and youthful appearance.",
    "Temel yağları almadan sağlıklı bir cilt görünümü için vazgeçilmezdir; ışıltılı ve genç bir görünüm sağlar.",
  ],
  [
    "Must have for all skin types, this serum supports a healthy, glowing complexion.",
    "Tüm cilt tipleri için vazgeçilmezdir; sağlıklı ve ışıltılı bir cilt görünümünü destekler.",
  ],
  [
    "Must have for daily use, it offers expert care in a convenient, easy-to-apply balm.",
    "Günlük kullanım için vazgeçilmezdir; pratik ve kolay uygulanan bir balmada uzman bakım sunar.",
  ],
  ["Universal Skin Compatibility", "Evrensel Cilt Uyumu"],
  ["Creamy, Blendable Texture", "Kremsi, Yayılabilir Doku"],
  ["Buildable Coverage (Medium to Full)", "Katmanlanabilir Kapatıcılık (Orta–Tam)"],
  ["Natural, Radiant Finish", "Doğal, Işıltılı Bitiş"],
  ["Long-Lasting Comfort Wear", "Uzun Süre Konforlu Kullanım"],
  ["Hydrating Formula", "Nemlendirici Formül"],
  ["Non-Comedogenic &amp; Lightweight", "Komedojenik Olmayan ve Hafif"],
  ["Non-Comedogenic & Lightweight", "Komedojenik Olmayan ve Hafif"],
  ["Wide Shade Range", "Geniş Ton Yelpazesi"],
  ["Free from Harsh Chemicals", "Sert Kimyasallardan Arındırılmış"],
  ["Specially formulated to suit dry, oily, combination, and sensitive skin, making it a go-to base product for every skin type.", "Kuru, yağlı, karma ve hassas ciltler için özel olarak formüle edilmiştir; her cilt tipi için ideal bir baz üründür."],
  ["The rich, creamy consistency melts into the skin, offering seamless coverage without feeling heavy or greasy. Blends effortlessly for a smooth, even complexion.", "Zengin kremsi kıvam cilde nüfuz eder; ağır veya yağlı hissettirmeden kusursuz kapatıcılık sunar. Pürüzsüz ve eşit bir ten için kolayca yayılır."],
  ["Easily customizable coverage — apply a thin layer for a natural, everyday look or build it up to conceal blemishes, redness, and uneven tone.", "Kolayca ayarlanabilir kapatıcılık — doğal günlük görünüm için ince katman veya leke, kızarıklık ve ton eşitsizliği için katmanlayın."],
  ["Leaves skin with a healthy, satin-like glow — not too matte and not too shiny. Perfect for achieving a flawless, skin-like finish.", "Cilde sağlıklı, satenimsi bir ışıltı verir — ne çok mat ne çok parlak. Kusursuz, doğal ten bitişi için mükemmeldir."],
  ["Designed to stay put for up to 12 hours without cracking, caking, or settling into fine lines. Ideal for all-day confidence.", "12 saate kadar çatlamadan, topaklanmadan ve ince çizgilere dolmadan kalacak şekilde tasarlanmıştır. Tüm gün özgüven için idealdir."],
  ["Enriched with moisturizing ingredients like hyaluronic acid, vitamin E, or squalane to keep skin nourished and plump throughout the day.", "Hyalüronik asit, E vitamini veya squalane gibi nemlendirici içeriklerle zenginleştirilmiştir; cildi gün boyu besler ve dolgun tutar."],
  ["Won't clog pores or trigger breakouts. Offers breathable coverage that feels light and fresh even with extended wear.", "Gözenekleri tıkamaz veya sivilceye yol açmaz. Uzun süreli kullanımda bile hafif ve ferah hissedilen nefes alabilir kapatıcılık sunar."],
  ["Available in inclusive shades with neutral, warm, and cool undertones to perfectly match diverse skin tones.", "Nötr, sıcak ve soğuk alt tonlarla çeşitli ten renklerine mükemmel uyum sağlayan kapsayıcı tonlarda mevcuttur."],
  ["Paraben-free, sulfate-free, cruelty-free, and safe for sensitive or allergy-prone skin.", "Paraben, sülfat içermez; hayvanlar üzerinde test edilmemiştir; hassas veya alerjiye eğilimli ciltler için güvenlidir."],
];
